modLoader="javafml"
loaderVersion="[47,)" # Forgeのバージョン範囲。通常、47はMinecraft 1.20.1に対応。
license="MIT" # Modのライセンス（例としてMITに設定）
[[mods]]
modId="difficulteye"
version="1.0.0"
displayName="Difficulteye"
description='''This mod increases the difficulty of Minecraft gameplay by introducing new mechanics.'''
authors="Yama_sheep"
[[dependencies.difficulteye]]
modId="forge"
mandatory=true
versionRange="[47,)" # Forge 47.x.x以上が必要
ordering="NONE"
side="BOTH"
[[dependencies.difficulteye]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)" # Minecraft 1.20.1以上、1.21未満
ordering="NONE"
side="BOTH"
